# Descrição

[Titanic - Machine Learning from Disaster](https://www.kaggle.com/competitions/titanic/data)

# Bibliotecas

In [61]:
import pandas as pd

[cookiecutter](https://www.cookiecutter.io/)  
[ydata-profiling](https://docs.profiling.ydata.ai/latest/)

# Importação dos dados

In [62]:
# Leitura do arquivo de dados
df = pd.read_csv("dados/train.csv")

In [63]:
# cinco primerias amostras
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Analise Exploratória

In [64]:
# Identificação dos atributos (Colunas)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [65]:
# Tipos da dada em cada atributo
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [66]:
# Tamanho da dataframe (Amostra (Número de linhas), Atributos (Número de colunas))
df.shape

(891, 12)

In [67]:
# Resumo descritivo das datafrane
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [68]:
# Dados ausentes em cada atributo
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [25]:
# Percentual dos dados ausentes em cada atributo
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [26]:
# Dados ausentes em cada amostra
df.isnull().sum(axis=1)

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [27]:
# Percentual de dados ausentes em amostra
df.isnull().mean(axis=1)

0      0.083333
1      0.000000
2      0.083333
3      0.000000
4      0.083333
         ...
886    0.083333
887    0.000000
888    0.166667
889    0.000000
890    0.083333
Length: 891, dtype: float64

## Documentação das funções

|Função|Descrição|Função|Descrição|
|--------|-------|------------|-------|
|[pd.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)| Leitura de arquivos .csv |[df.columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html#pandas.DataFrame.columns)|Identicação dos atributos (Nome das colunas)|
|[df.shape](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html#pandas.DataFrame.shape)|Tamanho do DataFrame|[df.describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe)|Descrição estatística básica do DataFrame|
|[df.sum](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum)|Soma dos valores|[df.mean](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html#pandas.DataFrame.mean)|Média dos valores|
|[df.dtypes](https://pandas.pydata.org/pandas-docs/version/2.2/reference/api/pandas.DataFrame.dtypes.html#pandas.DataFrame.dtypes)|Tipo de dado|[df.isnull](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html#pandas.DataFrame.isnull)|Determina se a celula tem algum valor|

# Limpeza dos dados

## Vazamento de informação

## Dados ausentes

In [69]:
# Identificação da posição dos valores ausentes
ausentes = [] # Armazenar a posição da cada valor ausente
for index in range(len(df.index)):
    for columns in range(len(df.columns)):
        if pd.isna(df.iloc[index,columns]):
            ausentes.append((index,columns))

print(f'Quantidade de valores ausentes: {len(ausentes)}')

"""
index = list(df.dropna().index) # Identifica os indexs dos valores ausentes
"""

Quantidade de valores ausentes: 866

'\nindex = list(df.dropna().index) # Identifica os indexs dos valores ausentes\n'

### Explicar a diferença entre `None` e `NaN`

### Diferença entre `==` e `is`

In [13]:
# Excluindo os valores ausentes, exclusão de toda as amostras com valores ausentes
for i in ausentes:
    try:  # Bloco try-except é 
        df.drop(i[0], inplace=True)
    except:
        continue

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [15]:
df.shape

(183, 12)

In [16]:
df.index = range(df.shape[0])

## Documentação das funções

|Método|Base de seleção|
|------|---------------|
|[df.loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc)|Usa labels (Nome de linhas/colunas)|
|[df.iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc)|Usa índices númericos (posição)|

# Treinamento